services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ./data:/src/app/data
      - ./models:/src/app/models
      - ./logs:/logs
    ports:
      - "8000:8000"
      - "6006:6006"
    profiles: ["cpu"]

  app-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./data:/src/app/data
      - ./models:/src/app/models
      - ./logs:/logs
    ports:
      - "8000:8000"
      - "6006:6006"
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]