services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8000:8000"
    profiles: ["cpu"]

  app-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8000:8000"
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]